# Generated by Django 5.2.1 on 2025-07-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('USER', 'USER'), ('ADMIN', 'ADMIN')], default='USER', max_length=50, null=True),
        ),
    ]
