# Generated by Django 5.2.1 on 2025-06-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
