# Generated by Django 5.2.1 on 2025-06-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_task_is_completed_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Due', 'Due')], default='Pending', max_length=20),
        ),
    ]
